# Copyright VMware, Inc.
# SPDX-License-Identifier: APACHE-2.0

version: '2'

services:
    kafka1:
        image: docker.io/bitnami/kafka:3.6
        networks:
            network:
                ipv4_address: 172.19.0.3
        ports:
            - '9097:9092'
        volumes:
            - 'kafka_data1:/bitnami'
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.19.0.3:9092
            - KAFKA_BROKER_ID=1
            - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@172.19.0.3:9093,2@172.19.0.4:9093,3@172.19.0.5:9093
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_NODE_ID=1
    kafka2:
        image: docker.io/bitnami/kafka:3.6
        networks:
            network:
                ipv4_address: 172.19.0.4
        ports:
            - '9098:9092'
        volumes:
            - 'kafka_data2:/bitnami'
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.19.0.4:9092
            - KAFKA_BROKER_ID=2
            - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@172.19.0.3:9093,2@172.19.0.4:9093,3@172.19.0.5:9093
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_NODE_ID=2
    kafka3:
        image: docker.io/bitnami/kafka:3.6
        networks:
            network:
                ipv4_address: 172.19.0.5
        ports:
            - '9099:9092'
        volumes:
            - 'kafka_data3:/bitnami'
        environment:
            - KAFKA_ENABLE_KRAFT=yes
            - KAFKA_CFG_PROCESS_ROLES=broker,controller
            - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
            - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
            - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
            - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.19.0.5:9092
            - KAFKA_BROKER_ID=3
            - KAFKA_KRAFT_CLUSTER_ID=LelM2dIFQkiUFvXCEcqRWA
            - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=1@172.19.0.3:9093,2@172.19.0.4:9093,3@172.19.0.5:9093
            - ALLOW_PLAINTEXT_LISTENER=yes
            - KAFKA_CFG_NODE_ID=3
volumes:
    kafka_data1:
        driver: local
    kafka_data2:
        driver: local
    kafka_data3:
        driver: local
networks:
    network:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: 172.19.0.0/16
